### ISSUE TITLE
Fazer Login

### ISSUE THREAD

**Issue by grdelemos** [ES-UFABC/Grupo-17-gerenciador_hoteis#5]
Cada usuário deve ter uma conta pessoal para acesso ao sistema, com login sendo feito por email e senha. Caso o usuário ainda não tenha conta, deve ser possível que ele faça o cadastro.

**Comment by claytonoliveira** [comment]
Como gerente de um hotel eu quero conseguir realizar o login no sistema utilizando email e senha para que eu possa entrar no sistema e gerenciar os quartos e recursos do hotel.
